import builtins from 'builtin-modules';
import child_process from 'child_process';
import esbuild from 'esbuild';
import fs from 'fs';
import process from 'process';

const prod = process.env.BUILD_ENV === 'production'

let runScriptPlugin = {
	name: 'run-script',
	setup(build) {
		build.onEnd(result => {
			if (result.errors.length > 0) {
				return
			}
			console.log('run sync-plugin.mjs')
			child_process.exec('node sync-plugin.mjs', (err, stdout, stderr) => {
				if (stdout) process.stdout.write(stdout)
				if (stderr) process.stderr.write(stderr)
				if (err) {
					console.error('run sync-plugin.mjs error:', err)
				}
			})
		})
	},
}

const ctx = await esbuild.context({
	banner: {
		js: '/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */',
	},
	define: {
		'process.env.BUILD_ENV': JSON.stringify(process.env.BUILD_ENV || ''),
	},
	entryPoints: ['src/main.ts', 'src/styles.css'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		...builtins],
	format: 'cjs',
	target: 'es2016',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir: 'build',
	legalComments: 'inline',
	plugins: [runScriptPlugin],
});

if (prod) {
	await ctx.rebuild();
	await ctx.dispose();
} else {
	await ctx.watch();
}
